### ISSUE TITLE
Copy not working

### ISSUE THREAD

**Issue by uriklar** [testing-library/which-query#10]
- `@testing-library/which-query` version: 0.02
- `node` version: 12.13.0
- `npm` version: 6.12.0
- `chrome` version: 83.0.4103.106

Relevant code or config

```html
<div class="BlockSidebarHeader__CloseXContainer-til1x7-1 eINDXn"><i color="#47505e" class="HBIcon__Icon-bzmbx4-0 gFzoVo"><svg width="16px" height="16px" viewBox="0 0 16 16"><title>close-16</title><desc>Created with Sketch.</desc><defs><path d="M12.5982389,2 L14,3.40176105 L9.401,8 L14,12.5982389 L12.5982389,14 L8,9.401 L3.40176105,14 L2,12.5982389 L6.598,8 L2,3.40176105 L3.40176105,2 L8,6.598 L12.5982389,2 Z" id="close16"></path></defs><g id="close-16" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><mask id="mask-2" fill="white"><use xlink:href="#close16"></use></mask><use id="Combined-Shape" fill="#000000" xlink:href="#close16"></use></g></svg></i></div>
```

What you did:
Right click on this element, copy as getBy

What happened:
Nothing was saved to my clipboard

I tried copying queries on other element on the page and they did work, but this element won't copy.
Let me know of any additional thing you'd like me to provide/investigate
Thanks!

**Comment by MatanBobi** [comment]
Hi @uriklar, thanks for posting this!
This might be related to #16, did you see any error in devtools?
Which OS are you using?

**Comment by nickmccurdy** [comment]
This project is no longer supported, but you can now use [Testing Playground](https://testing-playground.com/) which offers similar functionality and does not have this issue.
