### ISSUE TITLE
TypeError: Cannot read property 'closest' of null

### ISSUE THREAD

**Issue by DanielGibbsNZ** [testing-library/which-query#16]
- `@testing-library/which-query` version: 0.0.2
- **Browser version:** 87.0.4280.67 (Official Build) (x86_64)

**Reproduction steps**

1. Browse to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
2. Right-click on the "--Please choose an option--" select element and select *Testing Library* -> *Copy as getBy*

**Expected results**

A `getBy` query is copied to the clipboard.

**Actual results**

Nothing is copied to the clipboard, and an error is shown in the browser console:

```
Error in event handler: TypeError: Cannot read property 'closest' of null
    at getSuggestionFor (chrome-extension://olmmagdolfehlpjmbkmondggbebeimoh/dist/contentScript.js:21144:36)
    at chrome-extension://olmmagdolfehlpjmbkmondggbebeimoh/dist/contentScript.js:21033:28
```

The error seems to occur on the following line, presumably with a `null` element somehow:

```
const elementToResolve = element.closest(CLOSEST_SELECTOR) || element;
```

**Comment by MatanBobi** [comment]
Hi @DanielGibbsNZ, thanks for taking the time to post this one.
It looks like registering a `contextmenu` event on that document isn't working for some reason, you can give it a try also:
```
document.addEventListener(
  "contextmenu",
  (event) => {
    console.log(event)
  },
  true
);
```

I'll try to figure out what happens there when I get a chance, if you want you can too :)

**Comment by DanielGibbsNZ** [comment]
@MatanBobi Yes, I'm using macOS 11.0.1 (20B50).

I added the `contextmenu` listener as you suggested and can confirm that the event listener is not fired when right-clicking on any of the elements inside the "HTML Demo" container.

**Comment by MatanBobi** [comment]
@DanielGibbsNZ For some reason I can't reproduce this anymore.
Can you?

**Comment by DanielGibbsNZ** [comment]
@MatanBobi Yes, it still happens for me on Chrome 88.0.4324.96 (Official Build) (x86_64).

**Comment by azambranogbnt** [comment]
I am having the same problem I am trying to query items within a storybook.

**Chrome version:** Version 87.0.4280.141 (Official Build) (64-bit)
**O.S:** Ubuntu 18.04 bionic. x86_64 Linux 5.4.0-60-generic

**Comment by MatanBobi** [comment]
Ok so I've figured out the issue..
This happens when the `contextmenu` event happens within an `iframe`. Since the `iframe` doesn't propagate the event to the parent frame, our event handler doesn't catch the `contextmenu` event..
I think that we can also add a `contextmenu` event listener to every child frame but I don't think we want to, I'd be glad to hear thoughts :)

**Comment by nickmccurdy** [comment]
This project is no longer supported, but you can now use [Testing Playground](https://testing-playground.com/) which offers similar functionality and does not have this issue.
