### ISSUE TITLE
getByText queries don't escape quotes

### ISSUE THREAD

**Issue by DanielGibbsNZ** [testing-library/which-query#17]
- `@testing-library/which-query version:` 0.0.2
- **Browser version:** Chrome 87.0.4280.88 (Official Build) (x86_64)
- **OS:** macOS 11.0.1 (20B50)

**Reproduction steps**

1. View a page containing `<html><body><span>Shouldn't this be escaped?</span></body></html>` (may need to be served locally, viewing using file scheme doesn't seem to work)
2. Right-click on the text and select **Testing Library** -> **Copy as getBy**

**Expected results**

One of the following to be copied to the clipboard:

* `screen.getByText("Shouldn't this be escaped?")`
* `screen.getByText('Shouldn\'t this be escaped?')`

**Actual results**

`screen.getByText('Shouldn't this be escaped?')` is copied to the clipboard

**Suggested solution:**

The easiest fix seems to be escaping single quotes in the text, but I notice that when using **Copy as getBy** on a heading it uses a regular expression to match the text content (e.g. `screen.getByRole('heading', { name: /heading name/i }))`) so maybe this should be made consistent with that?

**Comment by nickmccurdy** [comment]
This project is no longer supported, but you can now use [Testing Playground](https://testing-playground.com/) which offers similar functionality.
